services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - internal

  rabbitmq:
    image: rabbitmq:3-management
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 5s
      timeout: 3s
      retries: 5  
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    networks:
      - internal
  
  redis:
    image: redis:latest
    container_name: redis_uptimemonitor
    restart: always
    # YO CHAI MAILE REDIS LE GARDA RAM FULL NA HOS BHANERA SETUP HANYA HO
    command: ["redis-server", "--maxmemory", "512mb", "--maxmemory-policy", "allkeys-lru"]
    volumes:
      - ./redis:/data
    networks:
      - internal

  alertmanager:
    image: prom/alertmanager:latest
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    env_file:
      - .env-development
    ports:
      - "9093:9093"
    networks:
      - internal
      - public
  
  prom-server:
    image: prom/prometheus
    volumes:
      - ./prometheus-config.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - public
      - internal
  
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prom-server
    networks:
      - public
      - internal

  loki:
    image: grafana/loki
    networks:
      - internal

  api-gateway:
    build: ./API_GATEWAY
    volumes:
      - ./API_GATEWAY:/app
    env_file:
      - .env-development
    ports:
      - "4000:4000"
    depends_on:
      - user-service
      - monitor-service
      - worker
    networks:
      - public
      - internal

  user-service:
    build: ./USER_SERVICE
    volumes:
      - ./USER_SERVICE:/app
    env_file:
      - .env-development
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - internal

  monitor-service:
    build: ./MONITOR_SERVICE
    volumes:
      - ./MONITOR_SERVICE:/app
    env_file:
      - .env-development
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_started
      redis:
        condition: service_started
    networks:
      - internal
      - public

  worker:
    build: ./WORKER
    volumes:
      - ./WORKER:/app
    env_file:
      - .env-development
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_started
    networks:
      - internal
      - public

volumes:
  pgdata:

networks:
  public:
  internal:
    internal: true
