services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5434:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5674:5672"
      - "15674:15672"
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
  
  redis:
    image: redis:latest
    container_name: redis_uptimemonitor
    restart: always
    ports:
      - "6380:6380"
    volumes:
      - ./redis:/data
    networks:
      - default

  api-gateway:
    build: ./API_GATEWAY
    ports:
      - "3000:3000"
    depends_on:
      - user-service
      - monitor-service
      - worker

  user-service:
    build: ./USER_SERVICE
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - postgres

  monitor-service:
    build: ./MONITOR_SERVICE
    ports:
      - "3002:3002"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - RABBITMQ_URL=${RABBITMQ_URL}
    depends_on:
      - postgres
      - rabbitmq
      - redis

  worker:
    build: ./WORKER
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - RABBITMQ_URL=${RABBITMQ_URL}
    depends_on:
      - postgres
      - rabbitmq

volumes:
  pgdata:
