FROM node:24-alpine

WORKDIR /app

# only the package.json is copied to leverage the docker cache
COPY package.json .

RUN yarn install

ENV NODE_ENV=DEVELOPMENT

# copy the rest of the files
COPY . .

EXPOSE 3001

CMD [ "yarn", "start:dev" ]