name: Integration

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
      - name: Install Prettier
        run: yarn global add prettier
      - name: Run Prettier
        run: |
          prettier --check "./API_GATEWAY/src/**/*.ts" \
                    "./MONITOR_SERVICE/src/**/*.ts" \
                    "./USER_SERVICE/src/**/*.ts" \
                    "./USER_SERVICE/__test__/*/*.ts" \
                    "./WORKER/src/**/*.ts"

  api-gateway:
    runs-on: ubuntu-latest
    needs: lint   
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
      - name: Build API_GATEWAY
        working-directory: ./API_GATEWAY
        run: |
          yarn install --frozen-lockfile
          yarn run build

  user-service:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
      - name: Build and test USER_SERVICE
        working-directory: ./USER_SERVICE
        run: |
          yarn install --frozen-lockfile
          yarn run build
          yarn run test

  monitor-service:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
      - name: Build MONITOR_SERVICE
        working-directory: ./MONITOR_SERVICE
        run: |
          yarn install --frozen-lockfile
          yarn run build

  worker:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
      - name: Build WORKER
        working-directory: ./WORKER
        run: |
          yarn install --frozen-lockfile
          yarn run build
