name: Integration

on:
  pull_request:
      branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
 buildAndTest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Build and test API_GATEWAY
      working-directory: ./API_GATEWAY
      run: |
        yarn run lint
        yarn install --frozen-lockfile
        yarn run build
    
    - name: Build and test USER_SERVICE
      working-directory: ./USER_SERVICE
      run: |
        yarn run lint
        yarn install --frozen-lockfile
        yarn run build
        yarn run test
    
    - name: Build and test MONITOR_SERVICE
      working-directory: ./MONITOR_SERVICE
      run: |
        yarn run lint
        yarn install --frozen-lockfile
        yarn run build
    
    - name: Build and test WORKER
      working-directory: ./WORKER
      run: |
        yarn run lint
        yarn install --frozen-lockfile
        yarn run build

